version: "3.9"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mydatabase}
      POSTGRES_USER: ${POSTGRES_USER:-myuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypassword}
    networks:
      - bschat-net
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  bot:
    depends_on:
      - db
    build:
      context: .
      target: deps # build only dependencies stage for dev
    env_file:
      - .env
    networks:
      - bschat-net
    volumes:
      # Mount everything *except node_modules*
      - .:/app:cached
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true # enables file watching on Windows/WSL
      - WATCHPACK_POLLING=true # for Webpack-based tools

networks:
  bschat-net:
    name: bschat-net
    driver: bridge

volumes:
  pgdata:
