services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: bschat
      POSTGRES_USER: bschat_user
      POSTGRES_PASSWORD: bschat_password
    networks:
      - bschat-net
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  bot:
    depends_on:
      - db
    env_file:
      - .env
    image: ghcr.io/khodis/prod-bschat-bot:latest
    networks:
      - bschat-net
    restart: always

networks:
  bschat-net:
    name: bschat-net
    driver: bridge

volumes:
  pgdata:
